app:
  minAge: 18

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop # ??? create-drop, validate, none ? ??????????? ?? ????? ????????????
    show-sql: true

  h2:
    console:
      enabled: true # ???????? ??????? H2
      path: /h2-console




